apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-deplyment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nodejs
  template:
    metadata:
        labels:
          app: nodejs
    spec:
      containers:
        - name: nodejs
          image: sharon111edapal/nodejs:$BUILD_ID


---

apiVersion: v1
kind: Service
metadata:
  name: nodejs-service
spec:
  type: NodePort
  selector:
    app: nodejs
  ports:
    - protocol: TCP
      port: 3005
      targetPort: 3005
      nodePort: 30001
